### ISSUE TITLE
Mailer fails to send

### ISSUE THREAD

**Issue by ChaseGiunta** [victor-in/Craft-Mailer#7] opened 2015-08-29 17:26 UTC
No errors in log. Craft Pro 2.4.2688 . I'm assuming this is no longer in development. Giving notice in case someone else tries this plugin out.

**Comment by klick** [comment] 2015-09-01 12:24
Yep. Seems to be.

**Comment by victor-in** [comment] 2015-09-10 19:37
Hey folks, I will try to take a look at this in the next few days. It worked on Craft 2.3, so I'll have to check the changelogs and figure out what has changed.

**Comment by klick** [comment] 2015-09-11 12:53
Cool. Good to hear!

**Comment by ChaseGiunta** [comment] 2015-09-11 15:14
:+1:  :smiley:

**Comment by victor-in** [comment] 2015-09-12 13:44
I just tested it locally and it worked for me, could you give me your setup?

Mine is:
Craft Pro 2.4.2692
PHP 5.5.8
Send using phpmail()

Are both logs empty (the mailer-one and crafts: /admin/utils/logs) ?
And could you test your connection (just to be sure) in the mail settings?

**Comment by ChaseGiunta** [comment] 2015-09-12 16:23
Craft Pro 2.4.2691
PHP 5.6
I'm sending using Mandrill through SMTP.
Craft system messages, as well as emails sent through Sprout Email, send just fine.

Mailer log is empty.
Here is the Craft log from sending to one user.
http://cl.ly/0D0J1t3Z0e0g

**Comment by victor-in** [comment] 2015-09-12 17:28
That's really weird. But just to make sure (sorry), there is the craft.log, the mailer.log and the record-logs (/admin/mailer#log). Is the record-log empty ("No errors") or non-existent?

**Comment by ChaseGiunta** [comment] 2015-09-12 17:37
Is this what you're referring to?
![image](https://cloud.githubusercontent.com/assets/1377169/9832885/96b2a496-594a-11e5-8df3-50eab988a478.png)
That is what I thought you were referring to when mentioning mailer.log ... Though, there is no log file named `mailer.log` in the usual log location (`craft/storage/runtimes/logs/`)

**Comment by victor-in** [comment] 2015-09-12 19:21
Ok, thanks. I've just updated the plugin with additional logging points. The log should show nox exactly the point where the error occures.

Could you please:
Install the new version,
enable devMode,
run the plugin,
and send me the mailer.log (/craft/storage/runtime/logs)

**Comment by ChaseGiunta** [comment] 2015-09-12 20:20
It still seems like Mailer is not creating a log file. There is no log present for mailer in `craft/storage/runtimes/logs/`

I've also tried changing mail settings from SMTP(Mandrill) to PHP Mail, and toggling off all plugin options, with still no success...

Another thing to note, Mailer doesn't attempt to display a flash message. I assume, or I would hope, when the plugin is functioning correctly, that it would display a message at the top saying "Your email has been sent" or something to that effect. That does not show. Not sure if it's relevant or not.

@klick can you confirm this as well?

**Comment by victor-in** [comment] 2015-09-12 20:38
Ok, this is really weird. 
If you have devMode enabled the first log entry should be created from the controller after submiting the form ( [here](https://github.com/victor-in/Craft-Mailer/blob/master/mailer/controllers/Mailer_FormController.php#L54) or [here](https://github.com/victor-in/Craft-Mailer/blob/master/mailer/controllers/Mailer_FormController.php#L81) ), at the same time when the flash messages are triggered.

Since you don't get any errors or warnings the controller action isn't getting triggered.
To make sure: Could you submit the form with empty fields?

Since the rest of your installation works fine, the most probable cause will be some kind of incompatibility with another plugin. Could you disable all your other plugins and check again?

**Comment by ChaseGiunta** [comment] 2015-09-12 20:50
Yep, DevMode is on. And you're right, it does allow me submit the form with entry fields. Just reloads the page. I've deleted every other plugin than Mailer. Still no success... Weird. Would be helpful if we had some more cases other than mine to confirm.

**Comment by victor-in** [comment] 2015-09-12 21:03
@klick Do you have the same symptoms on your end?

@ChaseGiunta If it runs on my end, isn't caused by the enviroment and also not by other plugins, my last guess would be the craft config file. Could you post it?

**Comment by ChaseGiunta** [comment] 2015-09-12 21:10
Even if I put in a completely different controller action in the form action (like the saveUser actions `users/saveUser`), it gives me no error, nothing. Clearing out my config completely changes nothing... Unrelated, but clicking on the variable buttons also throw a JS error `Uncaught Error: No such method "insertText" for Redactor`

**Comment by ChaseGiunta** [comment] 2015-09-12 21:15
Victor, I believe it has to do with your Send button.
You're using `<a href="" class="btn submit formsubmit last" data-icon="share">Send</a>` with the send button.
Replacing with `<input type="submit" class="btn submit" value="Save">` throws an error for me. I'm assuming it will also actually send an email now.

**Comment by ChaseGiunta** [comment] 2015-09-12 21:26
Well, replacing the Send button at least gets me the flash messages, and **now** I'm getting mailer.log in my logs folder, but unfortunately, still not sending.
```
2015/09/12 21:23:26 [info] [plugin] FormData valid
in /Users/ChaseGiunta/Git/craft/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/controllers/Mailer_FormController.php (81)
in /Users/ChaseGiunta/Git/craft/craft/app/etc/web/WebApp.php (784)
2015/09/12 21:23:26 [info] [plugin] Creating Custom Mailer_RecipientsModel
in /Users/ChaseGiunta/Git/craft/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/services/Mailer_MainService.php (32)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/controllers/Mailer_FormController.php (84)
2015/09/12 21:23:26 [info] [plugin] Custom Mailer_RecipientsModel validation successful
in /Users/ChaseGiunta/Git/craft/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/services/Mailer_MainService.php (53)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/controllers/Mailer_FormController.php (84)
2015/09/12 21:23:26 [info] [plugin] Create new MailerTask: Mailer: Custom
in /Users/ChaseGiunta/Git/craft/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/services/Mailer_MainService.php (144)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/services/Mailer_MainService.php (57)
2015/09/12 21:23:26 [info] [plugin] New MailerTask successfully created: "Mailer: Custom"
in /Users/ChaseGiunta/Git/craft/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/services/Mailer_MainService.php (156)
in /Users/ChaseGiunta/Git/craft/craft/plugins/mailer/services/Mailer_MainService.php (57)

******************************************************************************************************
```

**Comment by ChaseGiunta** [comment] 2015-09-12 21:34
I successfully got Mailer to send a message.
I think my issue was a two-part problem.
1) The Send Button currently does not fire to any controller in it's current `<a href="#"> format.
Fixing this fired the controller, and I received my logs.
2) My local environment, for whatever reason, was not working with Mailer (through SMTP, didn't test PHP Mail). But I was able to send successfully on my production environment.

**Comment by victor-in** [comment] 2015-09-12 21:42
1) Glad you got it sorted out. I just updated the button just in case, although I still don't understand how it could work on my end. (Maybe some kind of AdBlocker or no-js browser-plugin?)

2) Sometimes the background task needs a few seconds to start up, so you don't see errors in your log right away. Did the log show errors eventually or was **New MailerTask successfully created: "Mailer: Custom"** the last entry?

**Comment by ChaseGiunta** [comment] 2015-09-12 22:10
New MailerTask successfully created was the last entry... Tried both custom and selecting a user... But again, just on my local environment! Which I can live with :) It's production that counts.

And for the record, I did try the old button in a 3 different test browsers that I don't use (no adblocker or js plugins) FF, Safari, and Canary. No change. But yeah, very weird that it works on yours! 

You can probably close this issue for now and see if you get any more responses due to it not working on various environments. I have to assume @klick's issue was solved with the button update.

**Comment by klick** [comment] 2015-09-12 22:40
@victor-in  Seems to be working now! :) My set up was identical to the one of ChaseGiunta.
Do you still need the log?

**Comment by victor-in** [comment] 2015-09-13 11:21
Thanks guys, glad it works for you both now. I'll close this.

Btw: I'm going to rewrite this plugin for Craft 3, if you have any feedback, suggestions, feature-requests please don't hesitate to add them as an "issue".

**Closed** 2015-09-13 11:22 UTC
Labels: bug
